<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

    <ItemGroup>
      <Folder Include="Utilities\Converters\" />
    </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\MyLife.Common.BuildTimeAugmentation\MyLife.Common.BuildTimeAugmentation.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	</ItemGroup>
</Project>
