<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Android\MyLife.App.Android.UI.Mobile\MyLife.App.Android.UI.Mobile.csproj" />
        <ProjectReference Include="..\..\Android\MyLife.App.Android.UI.Watch\MyLife.App.Android.UI.Watch.csproj" />
        <ProjectReference Include="..\..\MyLife.App.Desktop\MyLife.App.Desktop.csproj" />
        <ProjectReference Include="..\..\Plugins\MyLife.App.Plugins.Content.Todo\MyLife.App.Plugins.Content.Todo.csproj" />
        <ProjectReference Include="..\MyLife.App.Shared.UI\MyLife.App.Shared.UI.csproj" />
    </ItemGroup>
</Project>
