<Project>
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<Copyright>(c) 2025 George Bilskiy. All rights reserved.</Copyright>
		<ImplicitUsings>enable</ImplicitUsings>

		<BuiltInComInteropSupport>false</BuiltInComInteropSupport>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		
	</PropertyGroup>

	<PropertyGroup>
		<AvaloniaVersion>11.3.2</AvaloniaVersion>
		<MVVMToolkitVersion>8.2.2</MVVMToolkitVersion>
	</PropertyGroup>

	<PropertyGroup Label="Avalonia">
		<AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
		<EnableAvaloniaXamlCompilation>True</EnableAvaloniaXamlCompilation>
		<AvaloniaXamlVerboseExceptions>False</AvaloniaXamlVerboseExceptions>
		<AvaloniaXamlIlDebuggerLaunch>False</AvaloniaXamlIlDebuggerLaunch>
	</PropertyGroup>
</Project>
